fileVersion: 1
id: "285"
mappingDefinitions:
  BRONZE:
    database: NY_TAXI
    schema: BRONZE
  GOLD:
    database: NY_TAXI
    schema: GOLD
  SILVER:
    database: NY_TAXI
    schema: SILVER
  SRC_WEATHER:
    database: GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI
    schema: STANDARD_TILE
name: Production
type: Environment
