fileVersion: 1
id: "285"
mappingDefinitions:
  BRONZE:
    database: ""
    schema: ""
  GOLD:
    database: ""
    schema: ""
  PUBLIC:
    database: ""
    schema: ""
  RAW:
    database: ""
    schema: ""
  SILVER:
    database: ""
    schema: ""
  SRC_WEATHER:
    database: GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI
    schema: STANDARD_TILE
name: Production
type: Environment
