fileVersion: 1
id: "285"
mappingDefinitions:
  BRONZE:
    database: NY_TAXI
    schema: LAND
  GOLD:
    database: DOUG_DB
    schema: PRD_GOLD
  PUBLIC:
    database: DOUG_DB
    schema: PUBLIC
  SILVER:
    database: DOUG_DB
    schema: DEV_SILVER
  SRC_WEATHER:
    database: GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI
    schema: STANDARD_TILE
name: Production
type: Environment
